# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt5', 'Android/Qt5', 'FreeBSD/Qt5', 'Windows/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kirigami': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kcontacts': '@stable'
    'frameworks/kpeople': '@stable'
    'pim/kpeoplevcard': '@stable'
    'libraries/kirigami-addons': '@latest'

- 'on': ['Linux/Qt6', 'Android/Qt6', 'FreeBSD/Qt6', 'Windows/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/kirigami': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kcontacts': '@latest-kf6'
    'frameworks/kpeople': '@latest-kf6'
    'pim/kpeoplevcard': '@latest-kf6'
    'libraries/kirigami-addons': '@latest-kf6'

Options:
    require-passing-tests-on: [ 'Linux', 'FreeBSD' ]
