# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kirigami': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kcontacts': '@stable'
    'frameworks/kpeople': '@stable'
    'pim/kpeoplevcard': '@stable'
    'libraries/kirigami-addons': '@latest'
